import PDFDocument from 'pdfkit';

interface ExportRow {
  id: string;
  startedAt: Date;
  completedAt: Date | null;
  conductedByName: string;
  status: string;
  totalItems: number;
  presentCount: number;
  missingCount: number;
  unresolvedCount: number;
  room: {
    id: string;
    name: string;
  } | null;
}

interface AuditHistoryPdfInput {
  officeLocationId: string;
  schoolName: string;
  generatedBy: string;
  sessions: ExportRow[];
  summary: {
    totalSessions: number;
    completedSessions: number;
    inProgressSessions: number;
    abandonedSessions: number;
    totalItems: number;
    presentItems: number;
    missingItems: number;
    unresolvedItems: number;
  };
  filters: {
    fiscalYear: string | null;
    status: string | null;
    from: string | null;
    to: string | null;
  };
}

function formatDateTime(date: Date | null) {
  if (!date) return 'N/A';
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatDate(date: Date | null) {
  if (!date) return 'N/A';
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });
}

function drawKeyValue(doc: PDFKit.PDFDocument, label: string, value: string) {
  doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
  doc.font('Helvetica').text(value);
}

export async function generateInventoryAuditHistoryPdf(
  data: AuditHistoryPdfInput
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 40, bottom: 40, left: 40, right: 40 },
      autoFirstPage: true,
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const drawHeader = () => {
      doc.font('Helvetica-Bold').fontSize(16).text('Inventory Audit History Report', {
        align: 'center',
      });
      doc.moveDown(0.8);

      doc.fontSize(10);
      drawKeyValue(doc, 'School', data.schoolName);
      drawKeyValue(doc, 'Generated By', data.generatedBy);
      drawKeyValue(doc, 'Generated At', formatDateTime(new Date()));
      drawKeyValue(doc, 'Fiscal Year', data.filters.fiscalYear ?? 'All');
      drawKeyValue(doc, 'Status', data.filters.status ?? 'All');
      drawKeyValue(
        doc,
        'Date Range',
        `${data.filters.from ?? 'Any'} to ${data.filters.to ?? 'Any'}`
      );

      doc.moveDown(0.8);
      doc.font('Helvetica-Bold').text('Summary');
      doc.font('Helvetica').text(
        `Sessions: ${data.summary.totalSessions} (Completed ${data.summary.completedSessions}, In Progress ${data.summary.inProgressSessions}, Abandoned ${data.summary.abandonedSessions})`
      );
      doc.text(
        `Items: ${data.summary.totalItems} total, ${data.summary.presentItems} present, ${data.summary.missingItems} missing, ${data.summary.unresolvedItems} unresolved`
      );

      doc.moveDown(0.8);
    };

    const ensureTableHeader = () => {
      if (doc.y > 690) {
        doc.addPage();
      }

      const y = doc.y;
      doc.fontSize(9).font('Helvetica-Bold');
      doc.text('Started', 40, y, { width: 90 });
      doc.text('Room', 132, y, { width: 95 });
      doc.text('Conducted By', 229, y, { width: 88 });
      doc.text('Status', 319, y, { width: 58 });
      doc.text('P/M', 379, y, { width: 58, align: 'right' });
      doc.text('Total', 439, y, { width: 45, align: 'right' });
      doc.text('Completed', 486, y, { width: 86, align: 'right' });

      doc.moveTo(40, y + 13).lineTo(572, y + 13).strokeColor('#BBBBBB').stroke();
      doc.moveDown(0.8);
    };

    drawHeader();
    ensureTableHeader();

    doc.font('Helvetica').fontSize(9);
    for (const session of data.sessions) {
      if (doc.y > 705) {
        doc.addPage();
        drawHeader();
        ensureTableHeader();
        doc.font('Helvetica').fontSize(9);
      }

      const rowY = doc.y;
      doc.text(formatDateTime(session.startedAt), 40, rowY, { width: 90 });
      doc.text(session.room?.name ?? 'N/A', 132, rowY, { width: 95 });
      doc.text(session.conductedByName || 'Unknown', 229, rowY, { width: 88 });
      doc.text(session.status.replace('_', ' '), 319, rowY, { width: 58 });
      doc.text(`${session.presentCount}/${session.missingCount}`, 379, rowY, {
        width: 58,
        align: 'right',
      });
      doc.text(String(session.totalItems), 439, rowY, { width: 45, align: 'right' });
      doc.text(formatDate(session.completedAt), 486, rowY, { width: 86, align: 'right' });

      doc.moveDown(1.2);
      doc.moveTo(40, doc.y).lineTo(572, doc.y).strokeColor('#EEEEEE').stroke();
      doc.moveDown(0.4);
    }

    if (data.sessions.length === 0) {
      doc.moveDown(0.6);
      doc.font('Helvetica-Oblique').text('No audit sessions found for selected filters.');
    }

    doc.end();
  });
}
